name: CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy backend service to ECS
      run: |
        aws ecs update-service \
          --cluster devops-cluster \
          --service backend-service \
          --force-new-deployment

    - name: Deploy frontend service to ECS
      run: |
        aws ecs update-service \
          --cluster devops-cluster \
          --service frontend-service \
          --force-new-deployment
