name: CI Pipeline

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  GIT_SHA: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # ---------------- Backend ----------------
    - name: Run backend tests
      run: |
        cd backend
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pytest

    # ---------------- Frontend ----------------
    - name: Run frontend tests
      run: |
        cd frontend
        npm ci
        npm test

    # ---------------- AWS Auth ----------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # ---------------- Docker Build: Backend ----------------
    - name: Build and push backend Docker image
      run: |
        cd backend
        docker build -t ${{ secrets.ECR_REPOSITORY_BACKEND }}:${GIT_SHA} .
        docker tag ${{ secrets.ECR_REPOSITORY_BACKEND }}:${GIT_SHA} ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_BACKEND }}:${GIT_SHA}
        docker push ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest

    # ---------------- Docker Build: Frontend ----------------
    - name: Build and push frontend Docker image
      run: |
        cd frontend
        docker build -t ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${GIT_SHA} .
        docker tag ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${GIT_SHA} ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_FRONTEND }}:${GIT_SHA}
        docker push ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest
